### PR TITLE
Update mdrepo.py

### PR DESCRIPTION
**Pull request by mrvanes**
This fix enables "bare" aliases to be succesfully retrievable via /alias requests. The main reason turns out to be an error in inlince doc in builtins.py.

### CODE REVIEW

**Comment by leifj** [comment]
Can you help me figure out why the test fails? I'm not ruling out the possibility that the test is broken or just failed randomly but I also wan't to make sure this fix doesn't break anything.

**Comment by mrvanes** [comment]
I'm not a travix expert, but I can try.
The test PR seem ok. But here I see things like  this:
```
root: ERROR: Generating RSA private key, 2048 bit long modulus
...........+++
...........................................................+++
unable to write 'random state'
e is 65537 (0x10001)
```
I just don't understand why a pull request with harmless comment does not trip on this as well?

**Comment by leifj** [comment]
Thats actually not an error but stdout from a successful test. Look for "FAIL"

**Comment by mrvanes** [comment]
The
```
- select as /ndn
```
in test_alias_ndn PyFFDTest fails, as is to be expected. Back to the drawing board to see how we can discriminate between true and false positives for the strip("/").

**Comment by mrvanes** [comment]
If you agree with the replacement of the strip("/") to store.py this PR looks fine now.

**Comment by leifj** [comment]
Reviewing old PRs (sorry about the delay) - can you help me unconflict this PR and also perhaps provide a testcase that demonstrates the breakage?

**Comment by mrvanes** [comment]
It's clear from the docs now that the alias is actually a path and needs the leading /

**Pull request closed without merging**
