### PR TITLE
Autoreload metadata

### PR DESCRIPTION
**Pull request by mrvanes**
This PR adds autoreloading on (local) filesystem metadata and fixes the commandline parsing to actually work for '-a'.

### CODE REVIEW

**Comment by sklemer1** [comment]
Nice! Thanks for that. Only problem I see is that your approach might conflict with #118 because of its hard dependency on cherrypy. Any idea on that?

**Comment by mrvanes** [comment]
@sklemer1 I really don't know enough about cherrypy and wsgi to understand #118 and see how this PR would break that. Also, I see that @leifj wants to move to flask, which renders #118 more or less void anyway?

The commandline parsing part however is a no-brainer, since that is completely broken as it is now.

**Comment by mrvanes** [comment]
Also, a cherrypy reload is quite expensive so we would like to see a metadata refresh instead but I couldn't find a way to understand how to reach the right (global?) object to call a reload on from within a Resource instantiation?

**Comment by sklemer1** [comment]
> @sklemer1 I really don't know enough about cherrypy and wsgi to understand #118 and see how this PR would break that. Also, I see that @leifj wants to move to flask, which renders #118 more or less void anyway?

Not really as WSGI is the underlying technology for both of them. Actually I'd also like to get rid of the python web server in between (let it be cherry or flask or bottle) and instead use pyff directly with (apache) wsgi -- but didn't find the time to look after the PR.


> The commandline parsing part however is a no-brainer, since that is completely broken as it is now.

Yep. Good catch, btw.


> I couldn't find a way to understand how to reach the right (global?) object to call a reload on from within a Resource instantiation

This is one for @leifj :).

**Comment by mrvanes** [comment]
To answer the question about hard dependancy on cherypy: I have an implementation lying around that implements inotify in a watchdog class, but the problem is that in the context of a Resource I see no way to actually trigger a metadata reload, as explained above, so I discarded that path for the time being.

**Comment by leifj** [comment]
This is really interesting work and I would actually like to merge the cmdline parsing issue separately. As for the other discussion it touches on several ideas I have for making pyFF less monolithic for instance by separating the load-and-normalize/post-load process into a message queue/worker pattern. In the context of the taking-ra21-to-service project we really should split off all the frontend bits into separate projects leaving pyFF as an "api core". This would make dynamic reloads etc a fairly trivial exercise.

**Comment by mrvanes** [comment]
The PR now only contains the autoreload metadata part

**Comment by leifj** [comment]
I'm going to close this PR since fetch has diverged so much. The api-refactory branch with its rewrite of all fetch using apscheduler maybe makes this easier to implement?!

**Pull request closed without merging**
