### PR TITLE
Only use path extension when no Accept header is present

### PR DESCRIPTION
**Pull request by skoranda**
If no Accept header is present or it is one of the wildcards
application/*, text/*, or */* then inspect the request path for
an extension for a hint on what format (e.g., XML or JSON) to return,
but do not inspect the path for an extension when an Accept header
is present and not one of the wildcards.

### All Submissions:

* [X] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [X] Have you added an explanation of what problem you are trying to solve with this PR?
* [X] Have you added information on what your changes do and why you chose this as your solution?
* [ ] Have you written new tests for your changes?
* [ ] Does your submission pass tests?
* [ ] This project follows PEP8 style guide. Have you run your code against the 'flake8' linter?

### CODE REVIEW

**Comment by skoranda** [comment]
I don't think the test failures have anything to do with this commit. If I am wrong please let me know and I can investigate.

**Comment by leifj** [comment]
I think the approach makes sense but I think we may need to make the switch configurable - something like pyff.content_negotiation_policy = [extension|access_header|adaptive]

- _extension_ is current (broken but legacy) behavior
- _adaptive_ is your proposal
- _access_header_ removes the split altogether

I propose we leave the default with extension to avoid unintended breakage and then we can transition to _access_header_ which is where we want pyFF to wind up eventually I think.

**Comment by skoranda** [comment]
Please review this latest push and if it is acceptable let me know and I can write some tests and update documentation.

**Comment by leifj** [comment]
it looks good but the coming and goings of commits make me a bit sea-sick...

**Comment by skoranda** [comment]
I will add documentation and a test(s) and then rebase and force push so the history will only show one commit.

**Pull request merged**
