### PR TITLE
Fix cmdline parser

### PR DESCRIPTION
**Pull request by mrvanes**
This is de cmdline parser part of #154 as per request of @leifj

### CODE REVIEW

**Comment by leifj** [comment]
Looking through all the PRs... I'm not 100% sure I understand this one. It seems safe enough but clearly the cmdline parser we have works so can you give a bit more background?

**Comment by mrvanes** [comment]
It's very simple, ```for i in ( ... )``` is syntactically wrong. It must be ```for i in [ ... ]```
The original commandline parsing code has never worked as intended.

**Comment by c00kiemon5ter** [comment]
In which version of python was that?

```
$ python
Python 2.7.16 (default, Mar  4 2019, 09:02:22) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> opts = ("-a", "--all")
>>> "-a" in opts
True
>>> 

$ python3
Python 3.7.3 (default, Mar 27 2019, 09:23:39) 
[Clang 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> opts = ("-a", "--all")
>>> "-a" in opts
True
>>> 
```

**Comment by mrvanes** [comment]
It's a coincidence that is works, you're not testing what you think you test...

**Comment by c00kiemon5ter** [comment]
The focus is on the `in` operator. The `for` in your response, I guess, should be `if` (as that is what the changes touch).

The `in` operator checks whether the left-hand value is part of the right-hand _iterable_. The problem with iterables is that `str` is an iterable, too. If the right-hand side is of string type, then you are not checking for membership, but for a substring. 

This is manifested in some of the options. `loglevel` is correct, but, `error-log`, `access-log`, `frequency`, `dir`, `proxy`, `allow_shutdown` and `version` are problematic. The actual needed change is to use `==` for those.

A a minimal test case `pyff --version` should be the same as `pyff --vers` which may be a problem.

**Comment by c00kiemon5ter** [comment]
> ```
> >>> '-l' in ('-log')
> True
> ```

In this expression, `('-log')` is not a tuple, it is a string. If you want a _single element tuple_ you have to add a leading comma. 

```
>>> var = ('-log')
>>> var
'-log'
>>> type(var)
<class 'str'>
>>> 
>>> var = ('-log',)
>>> var
('-log',)
>>> type(var)
<class 'tuple'>
```

**Comment by leifj** [comment]
ok I'l fix this in my api branch bc I've done stuff to the cmdline parser there - thx for the guidance guys!

**Comment by leifj** [comment]
Fixed in #159 (d613e7c)

**Comment by mrvanes** [comment]
Yes, @c00kiemon5ter I was doing two thing at a time, so I wrote ```for``` where I meant ```if```.
You're correct that the problem lies in strings being lists. The solution I suggest unifies all ```if``` statements, which I found cosmetically more attractive over diverging from ```in [ ... ]``` to ```==``` for single values ;)

**Pull request closed without merging**
