### PR TITLE
Trust Info metadata in JSON blob in entity attribute

### PR DESCRIPTION
**Pull request by enriquepablo**
### All Submissions:

* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Have you added an explanation of what problem you are trying to solve with this PR?
* [x] Have you added information on what your changes do and why you chose this as your solution?
* [x] Have you written new tests for your changes?
* [x] Does your submission pass tests?
* [ ] This project follows PEP8 style guide. Have you run your code against the 'flake8' linter?

### CODE REVIEW

**Review by mikaelfrykholm — APPROVED** [review]
Looks good to me. I tested with some hacked up metadata.

**Comment by alexstuart** [comment]
Hi @enriquepablo , the [REFEDS Working Group](https://wiki.refeds.org/display/GROUPS/SeamlessAccess+Trustinfo+Metadata+Working+Group) hasn't finalised the specification of entity attribute yet, so it might be premature to code `http://refeds.org/entity-selection-profile` in. When are you looking to land this change?

**Comment by enriquepablo** [comment]
We were going to put this into staging as soon as it was merged and released. The idea is to 1st check that it does not break the current workflow, and then deploy the mdq service that knows how to use the new data produced by pyff, and then deploy the discovery service that knows how to use the new mdq service (all should be backwards compatible). So to reach production it's still some time.

**Comment by enriquepablo** [comment]
(Sorry I sent the prev message too soon)
To be safer, I can put aside the [add pipe to extract trustinfo from entity attribute](https://github.com/IdentityPython/pyFF/pull/271/commits/4a30461518d022c7697b1a2e6091ffad28273cc5) commit aside in another branch until the specification is finalized.

**Comment by leifj** [comment]
are we ready to merge this?

**Comment by enriquepablo** [comment]
Yes. If the working group ends up with a different specification, we will do a later update.

**Pull request merged**
