### PR TITLE
SAMLStoreBase search lookup "in" and not "startswith"

### PR DESCRIPTION
**Pull request by peppelinux**
With this PR I can have a more flexible searches, the query now will not be based anymore on the matching of the initial digits but it will use a "contains" lookup.

this permit us to easily filter from this string, using "bad" as search keyword:
"http://bad-idp.testprovider.eu"
following the matching lookup.

Hope you'll enjoy, I developed this because some of my IDP do not have a good display name, this could force my users to type something like "https://thatword" before getting some good result out.

I also think, if you agree, to put an option to let the sysadmin decide how the lookup should be done, with which pattern, if startswith or contains. Probably a `re.match` would be better if you also agree.

### All Submissions:

* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Have you added an explanation of what problem you are trying to solve with this PR?
* [x] Have you added information on what your changes do and why you chose this as your solution?
* [ ] Have you written new tests for your changes?
* [x] Does your submission pass tests?
* [x] This project follows PEP8 style guide. Have you run your code against the 'flake8' linter?

### CODE REVIEW

**Comment by leifj** [comment]
I like the idea of flexible search that is user-configurable. Can you update the PR along those lines? Also can you take a look (if you have the time) at the api-refactory branch where this search is partly moved to the api.py to make sure your approach works and is reasonably easy to port after I merge. Alternatively maybe we merge this PR after that.

**Comment by peppelinux** [comment]
Good to hear you soon,
I saw the api-refactor branch, I think that is a very good step to decouple frontend and core-system with the help of an API. Regarding your indications I can tell you that this PR would also be applied without any conflicts in api-refactor. About the possibility to have a more configurable way to do searches I'll would like to go more in the deep in this, so  I'd like to talk about the following points. Another raccomendation would also be: please take what I say with a bit of salt, I'm just a programmer, you instead are the author of all this!

`argparse` refactor
------------------------
Instead of https://github.com/IdentityPython/pyFF/commit/fef51f030615cd3096dc6bc35ce0b2bae8a9da62#diff-ad3a5319bdade886d309889c72930e3cR89
I think that would it better use `argparse`, I used and know it very well, it's builtin in stdlib and I can tell you that it's a real stop-application. I have a lot of example with `argparse`, this is [one of them](https://github.com/peppelinux/pyDHCPStarvator/blob/master/starvit.py#L66). This way we can store default constants entirely in a settings.py file and import them in the argparse menu. Each options could be optionally overloaded with another file if it had been entered as option inline argument (`-f custom-local-settings.py`).  The presence of any other single option entered inline should rewrite its value globally as well. This could be good enough to manage the emerging complexity.

`pyff.costants`
-----------------
This is the key to deal with runtime behaviour customizations, you used a class called `Config` to store all those informations, we can use a simple file called `settings.py` with variables name like `GOOGLE_APY_KEY`, to be taken in `Config`. I think that the starting point could be the previous point related to `argparse`

API approach
-----------------
I've been using Django for 12 year now, and I know that the 50% of the code I read in pyFF, as in many others IdentityPython products, could be delegated to a mature web framework if it had been used. The Server behaviour, its http response Headers, the data persistence, the use of SQL or noSQL storage and many other features related to data validation, urls routings, cookie and general security, all those things that will take a lot of time  when developed and mantained from scratch. One of the best API framework I saw in my life is Django-REST but also [django-tastypie](https://django-tastypie.readthedocs.io/en/latest/) if developing time is poor. If a refactor based on Django could be a good task for the present, or the future, consider me available. At this time I can adapt my approach on your and follow your way the best I can.

If we would move to a flexible search we could discuss the need of a refactor of all the custom configuration behaviours if you agree, then this option would come in advance, as naturally as possible. Hope to have write something clear, my excuses in advance!

**Comment by leifj** [comment]
> Good to hear you soon,
> I saw the api-refactor branch, I think that is a very good step to decouple frontend and core-system with the help of an API. Regarding your indications I can tell you that this PR would also be applied without any conflicts in api-refactor. About the possibility to have a more configurable way to do searches 

I know there are no conflicts. However note that the search is duplicated in api.py...

>I'll would like to go more in the deep in this, so I'd like to talk about the following points. Another >raccomendation would also be: please take what I say with a bit of salt, I'm just a programmer, you >instead are the author of all this!
>

:-)
 
> ## `argparse` refactor
> Instead of [fef51f0#diff-ad3a5319bdade886d309889c72930e3cR89](https://github.com/IdentityPython/pyFF/commit/fef51f030615cd3096dc6bc35ce0b2bae8a9da62#diff-ad3a5319bdade886d309889c72930e3cR89)
> I think that would it better use `argparse`, I used and know it very well, it's builtin in stdlib and I can tell you that it's a real stop-application. I have a lot of example with `argparse`, this is [one of them](https://github.com/peppelinux/pyDHCPStarvator/blob/master/starvit.py#L66). This way we can store default constants entirely in a settings.py file and import them in the argparse menu. Each options could be optionally overloaded with another file if it had been entered as option inline argument (`-f custom-local-settings.py`). The presence of any other single option entered inline should rewrite its value globally as well. This could be good enough to manage the emerging complexity.

That sounds like an interesting idea. I will investigate this after I merge api-refactory

> 
> ## `pyff.costants`
> This is the key to deal with runtime behaviour customizations, you used a class called `Config` to store all those informations, we can use a simple file called `settings.py` with variables name like `GOOGLE_APY_KEY`, to be taken in `Config`. I think that the starting point could be the previous point related to `argparse`
> 

imo settings-as-code is a foot-gun. I am by no means married to this particular config file format but config files should not be Turing complete.

> ## API approach
> I've been using Django for 12 year now, and I know that the 50% of the code I read in pyFF, as in many others IdentityPython products, could be delegated to a mature web framework if it had been used. The Server behaviour, its http response Headers, the data persistence, the use of SQL or noSQL storage and many other features related to data validation, urls routings, cookie and general security, all those things that will take a lot of time when developed and mantained from scratch. One of the best API framework I saw in my life is Django-REST but also [django-tastypie](https://django-tastypie.readthedocs.io/en/latest/) if developing time is poor. If a refactor based on Django could be a good task for the present, or the future, consider me available. At this time I can adapt my approach on your and follow your way the best I can.
> 

We have discussed similar ideas on some of our f2f meetings. A move in this direction is not impossible in the future. We'll see.

> If we would move to a flexible search we could discuss the need of a refactor of all the custom configuration behaviours if you agree, then this option would come in advance, as naturally as possible. Hope to have write something clear, my excuses in advance!

**Comment by c00kiemon5ter** [comment]
> > ## `argparse` refactor
> > Instead of [fef51f0#diff-ad3a5319bdade886d309889c72930e3cR89](https://github.com/IdentityPython/pyFF/commit/fef51f030615cd3096dc6bc35ce0b2bae8a9da62#diff-ad3a5319bdade886d309889c72930e3cR89)
> > I think that would it better use `argparse`, I used and know it very well, it's builtin in stdlib and I can tell you that it's a real stop-application. I have a lot of example with `argparse`, this is [one of them](https://github.com/peppelinux/pyDHCPStarvator/blob/master/starvit.py#L66). This way we can store default constants entirely in a settings.py file and import them in the argparse menu. Each options could be optionally overloaded with another file if it had been entered as option inline argument (`-f custom-local-settings.py`). The presence of any other single option entered inline should rewrite its value globally as well. This could be good enough to manage the emerging complexity.
> 
> That sounds like an interesting idea. I will investigate this after I merge api-refactory
> 

see also [docopt](http://docopt.org/)

**Comment by leifj** [comment]
@c00kiemon5ter is this still needed or was this already handled in the merge of the api refactor branch? Looking at the diff it looks like we are already doing the right thing with matching.

**Comment by c00kiemon5ter** [comment]
Yes, I think we are doing the right thing.

Since I looked at this, I will write a small summary of the process as I read it:
1. we get a query string
2. we lower-case it
3. we wrap it into a list
4. we try to match it with an entity
5. we extract specific attributes from the metadata of the entity (see `_strings(elt)` -- DisplayName, ServiceName, OrganizationDisplayName, OrganizationName, Keywords, Scope)
6. for each attribute
    1. we lower-case the attributes
    2. we check if the query string is contained in the attribute
    3. if it is, we have a match!

With this patch, the attribute string is broken into tokens 
and we try to match the query against each token.

This means that mutli-word queries will never match.
So, I think the current behaviour is fine.

**Pull request closed without merging**
